[project]
name = "superstore-sales-project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "folium>=0.20.0",
    "matplotlib>=3.10.0",
    "pandas>=2.3.3",
    "plotly>=6.4.0",
    "prophet>=1.3.0",
    "psycopg2>=2.9.11",
    "python-stats>=1.0.1",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.44",
    "streamlit>=1.54.0",
    "streamlit-folium>=0.26.1",
    "ydata-profiling[notebook,unicode]>=4.17.0",
]
